record_path: /home/airo/aloha_dataset/raw_data
converted_path: /home/airo/aloha_dataset/converted
topic_names:
 - /cam_high/image_compressed
 - /cam_left_wrist/image_compressed
 - /cam_low/image_compressed
 - /cam_right_wrist/image_compressed
 - /left_arm/joint_ctrl
 - /left_arm/joint_states
 - /right_arm/joint_ctrl
 - /right_arm/joint_states
 - /tf